# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/zte/dana/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
    vendor/zte/dana/proprietary/lib/libaudioalsa.so:obj/lib/libaudioalsa.so \
    vendor/zte/dana/proprietary/lib/libacdbloader.so:obj/lib/libacdbloader.so \
    vendor/zte/dana/proprietary/lib/libmmjpeg.so:obj/lib/libmmjpeg.so

# bin
PRODUCT_COPY_FILES += \
  vendor/zte/dana/proprietary/bin/akmd8962_new:system/bin/akmd8962_new \
  vendor/zte/dana/proprietary/bin/ATFWD-daemon:system/bin/ATFWD-daemon \
  vendor/zte/dana/proprietary/bin/bridgemgrd:system/bin/bridgemgrd \
  vendor/zte/dana/proprietary/bin/ccid_daemon:system/bin/ccid_daemon \
  vendor/zte/dana/proprietary/bin/cnd:system/bin/cnd \
  vendor/zte/dana/proprietary/bin/ds_fmc_appd:system/bin/ds_fmc_appd \
  vendor/zte/dana/proprietary/bin/gdbserver:system/bin/gdbserver \
  vendor/zte/dana/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
  vendor/zte/dana/proprietary/bin/mm-pp-daemon:system/bin/mm-pp-daemon \
  vendor/zte/dana/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
  vendor/zte/dana/proprietary/bin/mpdecision:system/bin/mpdecision \
  vendor/zte/dana/proprietary/bin/netmgrd:system/bin/netmgrd \
  vendor/zte/dana/proprietary/bin/port-bridge:system/bin/port-bridge \
  vendor/zte/dana/proprietary/bin/pppd:system/bin/pppd \
  vendor/zte/dana/proprietary/bin/ppptunl:system/bin/ppptunl \
  vendor/zte/dana/proprietary/bin/profiler_daemon:system/bin/profiler_daemon \
  vendor/zte/dana/proprietary/bin/proximity.init:system/bin/proximity.init \
  vendor/zte/dana/proprietary/bin/qmiproxy:system/bin/qmiproxy \
  vendor/zte/dana/proprietary/bin/qmuxd:system/bin/qmuxd \
  vendor/zte/dana/proprietary/bin/qseecomd:system/bin/qseecomd \
  vendor/zte/dana/proprietary/bin/rild:system/bin/rild \
  vendor/zte/dana/proprietary/bin/rmt_storage:system/bin/rmt_storage \
  vendor/zte/dana/proprietary/bin/sensors.qcom:system/bin/sensors.qcom \
  vendor/zte/dana/proprietary/bin/thermald:system/bin/thermald \
  vendor/zte/dana/proprietary/bin/time_daemon:system/bin/time_daemon \
  vendor/zte/dana/proprietary/bin/usbhub:system/bin/usbhub \
  vendor/zte/dana/proprietary/bin/usbhub_init:system/bin/usbhub_init \
  vendor/zte/dana/proprietary/bin/usbmanutag:system/bin/usbmanutag \
  vendor/zte/dana/proprietary/bin/v4l2-qcamera-app:system/bin/v4l2-qcamera-app \
  vendor/zte/dana/proprietary/bin/zte_charger:system/bin/zte_charger \
  vendor/zte/dana/proprietary/bin/btnvtool:system/bin/btnvtool \
  vendor/zte/dana/proprietary/bin/fmconfig:system/bin/fmconfig \
  vendor/zte/dana/proprietary/bin/fm_qsoc_patches:system/bin/fm_qsoc_patches
  
# etc
PRODUCT_COPY_FILES += \
  vendor/zte/dana/proprietary/etc/firmware/wlan/prima/WCNSS_cfg.dat:system/etc/firmware/wlan/prima/WCNSS_cfg.dat \
  vendor/zte/dana/proprietary/etc/firmware/wlan/prima/WCNSS_qcom_cfg.ini:system/etc/firmware/wlan/prima/WCNSS_qcom_cfg.ini \
  vendor/zte/dana/proprietary/etc/firmware/wlan/prima/WCNSS_qcom_wlan_nv.bin:system/etc/firmware/wlan/prima/WCNSS_qcom_wlan_nv.bin \
  vendor/zte/dana/proprietary/etc/firmware/a225p5_pm4.fw:system/etc/firmware/a225p5_pm4.fw \
  vendor/zte/dana/proprietary/etc/firmware/a225_pfp.fw:system/etc/firmware/a225_pfp.fw \
  vendor/zte/dana/proprietary/etc/firmware/a225_pm4.fw:system/etc/firmware/a225_pm4.fw \
  vendor/zte/dana/proprietary/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
  vendor/zte/dana/proprietary/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
  vendor/zte/dana/proprietary/etc/firmware/cyttsp_8960_cdp.hex:system/etc/firmware/cyttsp_8960_cdp.hex \
  vendor/zte/dana/proprietary/etc/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \
  vendor/zte/dana/proprietary/etc/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw \
  vendor/zte/dana/proprietary/etc/firmware/vidc_1080p.fw:system/etc/firmware/vidc_1080p.fw \
  vendor/zte/dana/proprietary/etc/firmware/vidc.b00:system/etc/firmware/vidc.b00 \
  vendor/zte/dana/proprietary/etc/firmware/vidc.b01:system/etc/firmware/vidc.b01 \
  vendor/zte/dana/proprietary/etc/firmware/vidc.b02:system/etc/firmware/vidc.b02 \
  vendor/zte/dana/proprietary/etc/firmware/vidc.b03:system/etc/firmware/vidc.b03 \
  vendor/zte/dana/proprietary/etc/firmware/vidcfw.elf:system/etc/firmware/vidcfw.elf \
  vendor/zte/dana/proprietary/etc/firmware/vidc.mdt:system/etc/firmware/vidc.mdt \
  vendor/zte/dana/proprietary/etc/firmware/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \
  vendor/zte/dana/proprietary/etc/firmware/yamato_pm4.fw:system/etc/firmware/yamato_pm4.fw \
  
# lib
PRODUCT_COPY_FILES += \
  vendor/zte/dana/proprietary/lib/hw/alsa.msm8960.so:system/lib/hw/alsa.msm8960.so \
  vendor/zte/dana/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
  vendor/zte/dana/proprietary/lib/hw/lights.msm8960.so:system/lib/hw/lights.msm8960.so \
  vendor/zte/dana/proprietary/lib/hw/sensors.msm8960.so:system/lib/hw/sensors.msm8960.so \
  vendor/zte/dana/proprietary/lib/libacdbloader.so:system/lib/libacdbloader.so \
  vendor/zte/dana/proprietary/lib/libakmd.so:system/lib/libakmd.so \
  vendor/zte/dana/proprietary/lib/libami_sensor_mw.so:system/lib/libami_sensor_mw.so \
  vendor/zte/dana/proprietary/lib/libami.so:system/lib/libami.so \
  vendor/zte/dana/proprietary/lib/libaudcal.so:system/lib/libaudcal.so \
  vendor/zte/dana/proprietary/lib/libchromatix_imx074_default_video.so:system/lib/libchromatix_imx074_default_video.so \
  vendor/zte/dana/proprietary/lib/libchromatix_imx074_preview.so:system/lib/libchromatix_imx074_preview.so \
  vendor/zte/dana/proprietary/lib/libchromatix_imx074_video_hd.so:system/lib/libchromatix_imx074_video_hd.so \
  vendor/zte/dana/proprietary/lib/libchromatix_imx074_zsl.so:system/lib/libchromatix_imx074_zsl.so \
  vendor/zte/dana/proprietary/lib/libchromatix_imx091_default_video.so:system/lib/libchromatix_imx091_default_video.so \
  vendor/zte/dana/proprietary/lib/libchromatix_imx091_preview.so:system/lib/libchromatix_imx091_preview.so \
  vendor/zte/dana/proprietary/lib/libchromatix_imx091_video_hd.so:system/lib/libchromatix_imx091_video_hd.so \
  vendor/zte/dana/proprietary/lib/libchromatix_ov2720_default_video.so:system/lib/libchromatix_ov2720_default_video.so \
  vendor/zte/dana/proprietary/lib/libchromatix_ov2720_preview.so:system/lib/libchromatix_ov2720_preview.so \
  vendor/zte/dana/proprietary/lib/libchromatix_s5k3l1yx_default_video.so:system/lib/libchromatix_s5k3l1yx_default_video.so \
  vendor/zte/dana/proprietary/lib/libchromatix_s5k3l1yx_hfr_120fps.so:system/lib/libchromatix_s5k3l1yx_hfr_120fps.so \
  vendor/zte/dana/proprietary/lib/libchromatix_s5k3l1yx_hfr_60fps.so:system/lib/libchromatix_s5k3l1yx_hfr_60fps.so \
  vendor/zte/dana/proprietary/lib/libchromatix_s5k3l1yx_hfr_90fps.so:system/lib/libchromatix_s5k3l1yx_hfr_90fps.so \
  vendor/zte/dana/proprietary/lib/libchromatix_s5k3l1yx_preview.so:system/lib/libchromatix_s5k3l1yx_preview.so \
  vendor/zte/dana/proprietary/lib/libchromatix_s5k3l1yx_video_hd.so:system/lib/libchromatix_s5k3l1yx_video_hd.so \
  vendor/zte/dana/proprietary/lib/libchromatix_s5k3l1yx_zsl.so:system/lib/libchromatix_s5k3l1yx_zsl.so \
  vendor/zte/dana/proprietary/lib/libchromatix_s5k4e1_default_video.so:system/lib/libchromatix_s5k4e1_default_video.so \
  vendor/zte/dana/proprietary/lib/libchromatix_s5k4e1_preview.so:system/lib/libchromatix_s5k4e1_preview.so \
  vendor/zte/dana/proprietary/lib/libchromatix_vx6953_default_video.so:system/lib/libchromatix_vx6953_default_video.so \
  vendor/zte/dana/proprietary/lib/libchromatix_vx6953_preview.so:system/lib/libchromatix_vx6953_preview.so \
  vendor/zte/dana/proprietary/lib/libcneapiclient.so:system/lib/libcneapiclient.so \
  vendor/zte/dana/proprietary/lib/libcneqmiutils.so:system/lib/libcneqmiutils.so \
  vendor/zte/dana/proprietary/lib/libcneutils.so:system/lib/libcneutils.so \
  vendor/zte/dana/proprietary/lib/libdiag.so:system/lib/libdiag.so \
  vendor/zte/dana/proprietary/lib/libdivxdrmdecrypt.so:system/lib/libdivxdrmdecrypt.so \
  vendor/zte/dana/proprietary/lib/libDivxDrm.so:system/lib/libDivxDrm.so \
  vendor/zte/dana/proprietary/lib/libdrmdiag.so:system/lib/libdrmdiag.so \
  vendor/zte/dana/proprietary/lib/libdrmfs.so:system/lib/libdrmfs.so \
  vendor/zte/dana/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
  vendor/zte/dana/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
  vendor/zte/dana/proprietary/lib/libgemini.so:system/lib/libgemini.so \
  vendor/zte/dana/proprietary/lib/libgps.so:system/lib/libgps.so \
  vendor/zte/dana/proprietary/lib/libgps.utils.so:system/lib/libgps.utils.so \
  vendor/zte/dana/proprietary/lib/libidl.so:system/lib/libidl.so \
  vendor/zte/dana/proprietary/lib/libimage-jpeg-dec-omx-comp.so:system/lib/libimage-jpeg-dec-omx-comp.so \
  vendor/zte/dana/proprietary/lib/libimage-jpeg-enc-omx-comp.so:system/lib/libimage-jpeg-enc-omx-comp.so \
  vendor/zte/dana/proprietary/lib/libimage-omx-common.so:system/lib/libimage-omx-common.so \
  vendor/zte/dana/proprietary/lib/libinvensense_hal.so:system/lib/libinvensense_hal.so \
  vendor/zte/dana/proprietary/lib/libloc_adapter.so:system/lib/libloc_adapter.so \
  vendor/zte/dana/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
  vendor/zte/dana/proprietary/lib/libloc_eng.so:system/lib/libloc_eng.so \
  vendor/zte/dana/proprietary/lib/libloc_ext.so:system/lib/libloc_ext.so \
  vendor/zte/dana/proprietary/lib/liblocSDK_2.2.so:system/lib/liblocSDK_2.2.so \
  vendor/zte/dana/proprietary/lib/libmllite.so:system/lib/libmllite.so \
  vendor/zte/dana/proprietary/lib/libmm-abl-oem.so:system/lib/libmm-abl-oem.so \
  vendor/zte/dana/proprietary/lib/libmm-abl.so:system/lib/libmm-abl.so \
  vendor/zte/dana/proprietary/lib/libmm-audio-resampler.so:system/lib/libmm-audio-resampler.so \
  vendor/zte/dana/proprietary/lib/libmmcamera_faceproc.so:system/lib/libmmcamera_faceproc.so \
  vendor/zte/dana/proprietary/lib/libmmcamera_frameproc.so:system/lib/libmmcamera_frameproc.so \
  vendor/zte/dana/proprietary/lib/libmmcamera_statsproc30.so:system/lib/libmmcamera_statsproc30.so \
  vendor/zte/dana/proprietary/lib/libmm-color-convertor.so:system/lib/libmm-color-convertor.so \
  vendor/zte/dana/proprietary/lib/libsensor1.so:system/lib/libsensor1.so \
  vendor/zte/dana/proprietary/lib/libyas530.so:system/lib/libyas530.so \
  vendor/zte/dana/proprietary/lib/libmmhttpstack.so:system/lib/libmmhttpstack.so \
  vendor/zte/dana/proprietary/lib/libmmiipstreammmihttp.so:system/lib/libmmiipstreammmihttp.so \
  vendor/zte/dana/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
  vendor/zte/dana/proprietary/lib/libmmipstreamaal.so:system/lib/libmmipstreamaal.so \
  vendor/zte/dana/proprietary/lib/libmmipstreamnetwork.so:system/lib/libmmipstreamnetwork.so \
  vendor/zte/dana/proprietary/lib/libmmipstreamsourcehttp.so:system/lib/libmmipstreamsourcehttp.so \
  vendor/zte/dana/proprietary/lib/libmmipstreamutils.so:system/lib/libmmipstreamutils.so \
  vendor/zte/dana/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
  vendor/zte/dana/proprietary/lib/libmmjps.so:system/lib/libmmjps.so \
  vendor/zte/dana/proprietary/lib/libmmmpod.so:system/lib/libmmmpod.so \
  vendor/zte/dana/proprietary/lib/libmmmpo.so:system/lib/libmmmpo.so \
  vendor/zte/dana/proprietary/lib/libmmosal.so:system/lib/libmmosal.so \
  vendor/zte/dana/proprietary/lib/libmmparser.so:system/lib/libmmparser.so \
  vendor/zte/dana/proprietary/lib/libmmQSM.so:system/lib/libmmQSM.so \
  vendor/zte/dana/proprietary/lib/libmmrtpencoder.so:system/lib/libmmrtpencoder.so \
  vendor/zte/dana/proprietary/lib/libmmstereo.so:system/lib/libmmstereo.so \
  vendor/zte/dana/proprietary/lib/libmmstillomx.so:system/lib/libmmstillomx.so \
  vendor/zte/dana/proprietary/lib/libmmwfdinterface.so:system/lib/libmmwfdinterface.so \
  vendor/zte/dana/proprietary/lib/libmmwfdsinkinterface.so:system/lib/libmmwfdsinkinterface.so \
  vendor/zte/dana/proprietary/lib/libmmwfdsrcinterface.so:system/lib/libmmwfdsrcinterface.so \
  vendor/zte/dana/proprietary/lib/libmplmpu.so:system/lib/libmplmpu.so \
  vendor/zte/dana/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
  vendor/zte/dana/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
  vendor/zte/dana/proprietary/lib/libOmxAacDec.so:system/lib/libOmxAacDec.so \
  vendor/zte/dana/proprietary/lib/libOmxAacEnc.so:system/lib/libOmxAacEnc.so \
  vendor/zte/dana/proprietary/lib/libOmxAmrEnc.so:system/lib/libOmxAmrEnc.so \
  vendor/zte/dana/proprietary/lib/libOmxCore.so:system/lib/libOmxCore.so \
  vendor/zte/dana/proprietary/lib/libOmxEvrcDec.so:system/lib/libOmxEvrcDec.so \
  vendor/zte/dana/proprietary/lib/libOmxEvrcEnc.so:system/lib/libOmxEvrcEnc.so \
  vendor/zte/dana/proprietary/lib/libOmxMux.so:system/lib/libOmxMux.so \
  vendor/zte/dana/proprietary/lib/libOmxQcelp13Dec.so:system/lib/libOmxQcelp13Dec.so \
  vendor/zte/dana/proprietary/lib/libOmxQcelp13Enc.so:system/lib/libOmxQcelp13Enc.so \
  vendor/zte/dana/proprietary/lib/libOmxWmaDec.so:system/lib/libOmxWmaDec.so \
  vendor/zte/dana/proprietary/lib/libqc-opt.so:system/lib/libqc-opt.so \
  vendor/zte/dana/proprietary/lib/libqdi.so:system/lib/libqdi.so \
  vendor/zte/dana/proprietary/lib/libqdp.so:system/lib/libqdp.so \
  vendor/zte/dana/proprietary/lib/libqmi_cci.so:system/lib/libqmi_cci.so \
  vendor/zte/dana/proprietary/lib/libqmi_common_so.so:system/lib/libqmi_common_so.so \
  vendor/zte/dana/proprietary/lib/libqmi_csi.so:system/lib/libqmi_csi.so \
  vendor/zte/dana/proprietary/lib/libqmi_encdec.so:system/lib/libqmi_encdec.so \
  vendor/zte/dana/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
  vendor/zte/dana/proprietary/lib/libqmi.so:system/lib/libqmi.so \
  vendor/zte/dana/proprietary/lib/libQSEEComAPI.so:system/lib/libQSEEComAPI.so \
  vendor/zte/dana/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
  vendor/zte/dana/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
  vendor/zte/dana/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
  vendor/zte/dana/proprietary/lib/libril.so:system/lib/libril.so \
  vendor/zte/dana/proprietary/lib/libUw.so:system/lib/libUw.so \
  vendor/zte/dana/proprietary/lib/libv8.so:system/lib/libv8.so \
  vendor/zte/dana/proprietary/lib/libxml.so:system/lib/libxml.so \
  vendor/zte/dana/proprietary/lib/libmlplatform.so:system/lib/libmlplatform.so \
  vendor/zte/dana/proprietary/lib/libaudioalsa.so:system/lib/libaudioalsa.so

# key
PRODUCT_COPY_FILES += \
  vendor/zte/dana/proprietary/usr/idc/syna-touchscreen.idc:system/usr/idc/syna-touchscreen.idc \
  vendor/zte/dana/proprietary/usr/keylayout/atmel-touchscreen.kl:system/usr/keylayout/atmel-touchscreen.kl \
  vendor/zte/dana/proprietary/usr/keylayout/Fts-touchscreen.kl:system/usr/keylayout/Fts-touchscreen.kl \
  vendor/zte/dana/proprietary/usr/keylayout/keypad_8960.kl:system/usr/keylayout/keypad_8960.kl \
  vendor/zte/dana/proprietary/usr/keylayout/msm8960-snd-card_Button_Jack.kl:system/usr/keylayout/msm8960-snd-card_Button_Jack.kl \
  vendor/zte/dana/proprietary/usr/keylayout/syna-touchscreen.kl:system/usr/keylayout/syna-touchscreen.kl

# config
PRODUCT_COPY_FILES += \
  vendor/zte/dana/proprietary/etc/snd_soc_msm/DL_REC:system/etc/snd_soc_msm/DL_REC \
  vendor/zte/dana/proprietary/etc/snd_soc_msm/DL_REC_2x:system/etc/snd_soc_msm/DL_REC_2x \
  vendor/zte/dana/proprietary/etc/snd_soc_msm/FM_A2DP_REC:system/etc/snd_soc_msm/FM_A2DP_REC \
  vendor/zte/dana/proprietary/etc/snd_soc_msm/FM_A2DP_REC_2x:system/etc/snd_soc_msm/FM_A2DP_REC_2x \
  vendor/zte/dana/proprietary/etc/snd_soc_msm/FM_Digital_Radio:system/etc/snd_soc_msm/FM_Digital_Radio \
  vendor/zte/dana/proprietary/etc/snd_soc_msm/FM_Digital_Radio_2x:system/etc/snd_soc_msm/FM_Digital_Radio_2x \
  vendor/zte/dana/proprietary/etc/snd_soc_msm/FM_REC:system/etc/snd_soc_msm/FM_REC \
  vendor/zte/dana/proprietary/etc/snd_soc_msm/FM_REC_2x:system/etc/snd_soc_msm/FM_REC_2x \
  vendor/zte/dana/proprietary/etc/snd_soc_msm/HiFi:system/etc/snd_soc_msm/HiFi \
  vendor/zte/dana/proprietary/etc/snd_soc_msm/HiFi_2x:system/etc/snd_soc_msm/HiFi_2x \
  vendor/zte/dana/proprietary/etc/snd_soc_msm/HiFi_Low_Power:system/etc/snd_soc_msm/HiFi_Low_Power \
  vendor/zte/dana/proprietary/etc/snd_soc_msm/HiFi_Low_Power_2x:system/etc/snd_soc_msm/HiFi_Low_Power_2x \
  vendor/zte/dana/proprietary/etc/snd_soc_msm/HiFi_Rec:system/etc/snd_soc_msm/HiFi_Rec \
  vendor/zte/dana/proprietary/etc/snd_soc_msm/HiFi_Rec_2x:system/etc/snd_soc_msm/HiFi_Rec_2x \
  vendor/zte/dana/proprietary/etc/snd_soc_msm/snd_soc_msm:system/etc/snd_soc_msm/snd_soc_msm \
  vendor/zte/dana/proprietary/etc/snd_soc_msm/snd_soc_msm_2x:system/etc/snd_soc_msm/snd_soc_msm_2x \
  vendor/zte/dana/proprietary/etc/snd_soc_msm/UL_DL_REC:system/etc/snd_soc_msm/UL_DL_REC \
  vendor/zte/dana/proprietary/etc/snd_soc_msm/UL_DL_REC_2x:system/etc/snd_soc_msm/UL_DL_REC_2x \
  vendor/zte/dana/proprietary/etc/snd_soc_msm/Voice_Call:system/etc/snd_soc_msm/Voice_Call \
  vendor/zte/dana/proprietary/etc/snd_soc_msm/Voice_Call_2x:system/etc/snd_soc_msm/Voice_Call_2x \
  vendor/zte/dana/proprietary/etc/snd_soc_msm/Voice_Call_IP:system/etc/snd_soc_msm/Voice_Call_IP \
  vendor/zte/dana/proprietary/etc/snd_soc_msm/Voice_Call_IP_2x:system/etc/snd_soc_msm/Voice_Call_IP_2x \
  vendor/zte/dana/proprietary/etc/srs/srsmodels.lic:system/etc/srs/srsmodels.lic \
  vendor/zte/dana/proprietary/etc/srs/srs_processing.cfg:system/etc/srs/srs_processing.cfg \
  vendor/zte/dana/proprietary/etc/wifi/p2p_supplicant.conf:system/etc/wifi/p2p_supplicant.conf \
  vendor/zte/dana/proprietary/etc/wifi/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \
  vendor/zte/dana/proprietary/etc/init.ct_fmc.sh:system/etc/init.ct_fmc.sh \
  vendor/zte/dana/proprietary/etc/init.qcom.bt.sh:system/etc/init.qcom.bt.sh \
  vendor/zte/dana/proprietary/etc/init.qcom.coex.sh:system/etc/init.qcom.coex.sh \
  vendor/zte/dana/proprietary/etc/init.qcom.efs.sync.sh:system/etc/init.qcom.efs.sync.sh \
  vendor/zte/dana/proprietary/etc/init.qcom.fm.sh:system/etc/init.qcom.fm.sh \
  vendor/zte/dana/proprietary/etc/init.qcom.modem_links.sh:system/etc/init.qcom.modem_links.sh \
  vendor/zte/dana/proprietary/etc/init.qcom.post_boot.sh:system/etc/init.qcom.post_boot.sh \
  vendor/zte/dana/proprietary/etc/init.qcom.sdio.sh:system/etc/init.qcom.sdio.sh \
  vendor/zte/dana/proprietary/etc/init.qcom.wifi.sh:system/etc/init.qcom.wifi.sh \
  vendor/zte/dana/proprietary/etc/init.wlanprop.sh:system/etc/init.wlanprop.sh \
  vendor/zte/dana/proprietary/etc/media_codecs.xml:system/etc/media_codecs.xml \
  vendor/zte/dana/proprietary/etc/media_profiles.xml:system/etc/media_profiles.xml \
  vendor/zte/dana/proprietary/etc/thermald.conf:system/etc/thermald.conf \

# adreno
PRODUCT_COPY_FILES += \
  vendor/zte/dana/proprietary/lib/libsc-a2xx.so:system/lib/libsc-a2xx.so \
  vendor/zte/dana/proprietary/lib/libOpenVG.so:system/lib/libOpenVG.so \
  vendor/zte/dana/proprietary/lib/libC2D2.so:system/lib/libC2D2.so \
  vendor/zte/dana/proprietary/lib/libc2d2_z180.so:system/lib/libc2d2_z180.so \
  vendor/zte/dana/proprietary/lib/egl/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
  vendor/zte/dana/proprietary/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
  vendor/zte/dana/proprietary/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
  vendor/zte/dana/proprietary/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
  vendor/zte/dana/proprietary/lib/egl/libGLESv2S3D_adreno200.so:system/lib/egl/libGLESv2S3D_adreno200.so \
  vendor/zte/dana/proprietary/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
  vendor/zte/dana/proprietary/lib/libgsl.so:system/lib/libgsl.so \
